In [1]:
import pandas as pd

## GRU

### Battery Drain Comparison

In [2]:
df = pd.read_csv("./API_GRU.csv")
df.head()

,timestamp,cpu_usage,memory_usage,temperature,battery_level,battery_charging,upload_speed_kbps,download_speed_kbps,screen_on,brightness,battery_drain,predicted_drain_average,inference_time_ms
0,5/1/2026 10:38,55,65,38.0,50,0,8.770573,122.754200,1,23,-660,-333.01575,4169.728176
1,5/1/2026 10:38,55,65,38.0,50,0,8.770573,122.754200,1,23,-660,-336.80630,176.724687
2,5/1/2026 10:38,42,66,38.0,50,0,8.381533,59.084347,1,23,-390,-342.35532,176.040885
3,5/1/2026 10:38,39,66,38.0,50,0,3.413585,53.422348,1,23,-395,-344.14853,139.490208
4,5/1/2026 10:38,35,67,38.0,50,0,6.425407,108.144870,1,23,-286,-345.38885,118.480416

In [3]:
df[['battery_drain', 'predicted_drain_average']].mean()

battery_drain              16.992400
predicted_drain_average   -25.956244
dtype: float64

In [4]:
# Not Charging
df[df['battery_charging'] != 1][['battery_drain', 'predicted_drain_average']].mean()

battery_drain             -289.074458
predicted_drain_average   -330.814421
dtype: float64

In [5]:
# Charging
df[df['battery_charging'] == 1][['battery_drain', 'predicted_drain_average']].mean()

battery_drain              1856.654918
predicted_drain_average    1806.441303
dtype: float64

In [6]:
charging = df[df['battery_charging'] == 1]
not_charging = df[df['battery_charging'] != 1]

In [7]:
def percentage_diff(df):
    actual_mean = df['battery_drain'].mean()
    pred_mean = df['predicted_drain_average'].mean()

    perc = abs(actual_mean - pred_mean) / abs(actual_mean) * 100

    return actual_mean, pred_mean, perc

In [8]:
act_c, pred_c, perc_c = percentage_diff(charging)
act_nc, pred_nc, perc_nc = percentage_diff(not_charging)
act_all, pred_all, perc_all = percentage_diff(df)

In [9]:
print("== ALL ===")
print("Actual Mean:", act_all)
print("Predicted Mean:", pred_all)
print("Percentage Difference:", perc_all, "%")

print("\n=== CHARGING ===")
print("Actual Mean:", act_c)
print("Predicted Mean:", pred_c)
print("Percentage Difference:", perc_c, "")

print("\n=== NOT CHARGING ===")
print("Actual Mean:", act_nc)
print("Predicted Mean:", pred_nc)
print("Percentage Difference:", perc_nc, "%")

== ALL ===
Actual Mean: 16.992400327370515
Predicted Mean: -25.956244311001996
Percentage Difference: 252.75207628667368 %

=== CHARGING ===
Actual Mean: 1856.6549180327868
Predicted Mean: 1806.441302729508
Percentage Difference: 2.7045206309249186

=== NOT CHARGING ===
Actual Mean: -289.0744579299059
Predicted Mean: -330.8144206903041
Percentage Difference: 14.439173581541114 %

In [ ]:
# Inference
df['inference_time_ms'].describe()

### Graph

## CNN GRU

In [12]:
df_cnn = pd.read_csv("./API_CNN_GRU.csv")
df_cnn.head()

,timestamp,cpu_usage,memory_usage,temperature,battery_level,battery_charging,upload_speed_kbps,download_speed_kbps,screen_on,brightness,battery_drain,predicted_drain_average,inference_time_ms
0,2026-04-30 10:09:19,42,66,33.4,84,0,2.372091,0.218891,1,24,-228.0,-284.06293,2524.913645
1,2026-04-30 10:09:21,37,66,33.4,84,0,1.236759,0.497219,1,24,-256.0,-310.48780,311.548437
2,2026-04-30 10:09:25,43,66,33.4,84,0,5.511522,253.716920,1,24,-236.0,-310.25890,222.169739
3,2026-04-30 10:09:29,43,67,33.4,84,0,1.819063,0.304796,1,24,-257.0,-319.87054,159.743697
4,2026-04-30 10:09:33,50,67,33.4,84,0,4.055333,2.990146,1,24,-413.0,-301.71088,437.896250

In [13]:
df_cnn[['battery_drain', 'predicted_drain_average']].mean()

battery_drain             -103.408666
predicted_drain_average   -137.964038
dtype: float64

In [14]:
# Not Charging
df_cnn[df_cnn['battery_charging'] != 1][['battery_drain', 'predicted_drain_average']].mean()

battery_drain             -290.629143
predicted_drain_average   -302.460759
dtype: float64

In [15]:
# Charging
df_cnn[df_cnn['battery_charging'] == 1][['battery_drain', 'predicted_drain_average']].mean()

battery_drain              1332.653484
predicted_drain_average    1123.797064
dtype: float64

In [16]:
charging = df_cnn[df_cnn['battery_charging'] == 1]
not_charging = df_cnn[df_cnn['battery_charging'] != 1]

In [17]:
act_c, pred_c, perc_c = percentage_diff(charging)
act_nc, pred_nc, perc_nc = percentage_diff(not_charging)
act_all, pred_all, perc_all = percentage_diff(df_cnn)

In [18]:
print("== ALL ===")
print("Actual Mean:", act_all)
print("Predicted Mean:", pred_all)
print("Percentage Difference:", perc_all, "%")

print("\n=== CHARGING ===")
print("Actual Mean:", act_c)
print("Predicted Mean:", pred_c)
print("Percentage Difference:", perc_c, "")

print("\n=== NOT CHARGING ===")
print("Actual Mean:", act_nc)
print("Predicted Mean:", pred_nc)
print("Percentage Difference:", perc_nc, "%")

== ALL ===
Actual Mean: -103.40866637706343
Predicted Mean: -137.96403807391403
Percentage Difference: 33.416320805115 %

=== CHARGING ===
Actual Mean: 1332.653483992467
Predicted Mean: 1123.7970638996233
Percentage Difference: 15.672222569601175

=== NOT CHARGING ===
Actual Mean: -290.6291431377363
Predicted Mean: -302.4607592003437
Percentage Difference: 4.071035662449068 %

In [19]:
# Inference
df_cnn['inference_time_ms'].describe()

count    9208.000000
mean      229.395614
std       155.362416
min        99.926146
25%       165.999818
50%       201.854010
75%       261.934036
max      7380.025570
Name: inference_time_ms, dtype: float64