In [1]:
import pandas as pd

## GRU

### Battery Drain Comparison

In [2]:
df = pd.read_csv("./LOCAL_GRU.csv")
df.head()

,timestamp,cpu_usage,memory_usage,temperature,battery_level,battery_charging,upload_speed_kbps,download_speed_kbps,screen_on,brightness,battery_drain,predicted_drain_average,inference_time_ms
0,4/23/2026 22:20,26,67,36.3,50,1,0.650718,0.000000,1,21,3949,1095.76920,17.185885
1,4/23/2026 22:20,26,66,36.6,51,1,0.594367,0.374730,1,21,3969,1049.32600,9.546042
2,4/23/2026 22:20,35,67,36.6,51,1,0.044356,0.030857,1,21,3923,1006.00604,1.387604
3,4/23/2026 22:20,26,67,36.6,51,1,0.769046,0.574363,1,21,3964,972.66850,6.067604
4,4/23/2026 22:20,26,67,36.8,51,1,0.433491,0.546933,1,21,3940,943.25060,5.578020

In [3]:
df[['battery_drain', 'predicted_drain_average']].mean()

battery_drain              -3.221081
predicted_drain_average   -46.226998
dtype: float64

In [4]:
# Not Charging
df[df['battery_charging'] != 1][['battery_drain', 'predicted_drain_average']].mean()

battery_drain             -282.199647
predicted_drain_average   -301.729570
dtype: float64

In [5]:
# Charging
df[df['battery_charging'] == 1][['battery_drain', 'predicted_drain_average']].mean()

battery_drain              1574.513638
predicted_drain_average    1398.741639
dtype: float64

In [6]:
charging = df[df['battery_charging'] == 1]
not_charging = df[df['battery_charging'] != 1]

In [7]:
def percentage_diff(df):
    actual_mean = df['battery_drain'].mean()
    pred_mean = df['predicted_drain_average'].mean()

    perc = abs(actual_mean - pred_mean) / abs(actual_mean) * 100

    return actual_mean, pred_mean, perc

In [8]:
act_c, pred_c, perc_c = percentage_diff(charging)
act_nc, pred_nc, perc_nc = percentage_diff(not_charging)
act_all, pred_all, perc_all = percentage_diff(df)

In [9]:
print("== ALL ===")
print("Actual Mean:", act_all)
print("Predicted Mean:", pred_all)
print("Percentage Difference:", perc_all, "%")

print("\n=== CHARGING ===")
print("Actual Mean:", act_c)
print("Predicted Mean:", pred_c)
print("Percentage Difference:", perc_c, "")

print("\n=== NOT CHARGING ===")
print("Actual Mean:", act_nc)
print("Predicted Mean:", pred_nc)
print("Percentage Difference:", perc_nc, "%")

== ALL ===
Actual Mean: -3.2210805818517665
Predicted Mean: -46.226998005474094
Percentage Difference: 1335.1394456235137 %

=== CHARGING ===
Actual Mean: 1574.5136381098732
Predicted Mean: 1398.7416394083748
Percentage Difference: 11.163574226800863

=== NOT CHARGING ===
Actual Mean: -282.19964676312753
Predicted Mean: -301.7295700582048
Percentage Difference: 6.920605152801719 %

In [10]:
# Inference
df['inference_time_ms'].describe()

count    17324.000000
mean         2.716486
std          1.730199
min          0.526355
25%          1.360469
50%          1.870677
75%          4.125704
max         22.897084
Name: inference_time_ms, dtype: float64

### Graph

#### Predicted vs Actual

In [ ]:
#

## CNN GRU

In [11]:
df_cnn = pd.read_csv("./LOCAL_CNN_GRU.csv")
df_cnn.head()

,timestamp,cpu_usage,memory_usage,temperature,battery_level,battery_charging,upload_speed_kbps,download_speed_kbps,screen_on,brightness,battery_drain,predicted_drain_average,inference_time_ms
0,4/24/2026 11:29,53,69,34.0,48,0,9.745290,9.724471,1,23,-329,-256.58835,2.877448
1,4/24/2026 11:29,37,68,34.0,48,0,3.566566,0.894737,1,23,-273,-255.10776,3.124479
2,4/24/2026 11:29,35,68,34.0,48,0,0.231017,0.209972,1,23,-288,-301.81644,3.529896
3,4/24/2026 11:29,39,69,34.0,48,0,0.439453,0.369112,1,23,-260,-300.23970,1.408750
4,4/24/2026 11:30,49,68,34.0,48,0,0.129287,0.129287,1,23,-256,-278.74072,1.260417

In [12]:
df_cnn[['battery_drain', 'predicted_drain_average']].mean()

battery_drain              12.818965
predicted_drain_average    13.304010
dtype: float64

In [13]:
# Not Charging
df_cnn[df_cnn['battery_charging'] != 1][['battery_drain', 'predicted_drain_average']].mean()

battery_drain             -308.946858
predicted_drain_average   -240.594484
dtype: float64

In [14]:
# Charging
df_cnn[df_cnn['battery_charging'] == 1][['battery_drain', 'predicted_drain_average']].mean()

battery_drain              2219.379175
predicted_drain_average    1754.453234
dtype: float64

In [15]:
charging = df_cnn[df_cnn['battery_charging'] == 1]
not_charging = df_cnn[df_cnn['battery_charging'] != 1]

In [16]:
act_c, pred_c, perc_c = percentage_diff(charging)
act_nc, pred_nc, perc_nc = percentage_diff(not_charging)
act_all, pred_all, perc_all = percentage_diff(df_cnn)

In [17]:
print("== ALL ===")
print("Actual Mean:", act_all)
print("Predicted Mean:", pred_all)
print("Percentage Difference:", perc_all, "%")

print("\n=== CHARGING ===")
print("Actual Mean:", act_c)
print("Predicted Mean:", pred_c)
print("Percentage Difference:", perc_c, "%.2f")

print("\n=== NOT CHARGING ===")
print("Actual Mean:", act_nc)
print("Predicted Mean:", pred_nc)
print("Percentage Difference:", perc_nc, "%")

== ALL ===
Actual Mean: 12.818965187085903
Predicted Mean: 13.304009778733946
Percentage Difference: 3.7838045783655536 %

=== CHARGING ===
Actual Mean: 2219.379175443876
Predicted Mean: 1754.453233876932
Percentage Difference: 20.948468234318675 %.2f

=== NOT CHARGING ===
Actual Mean: -308.9468579954362
Predicted Mean: -240.5944838002687
Percentage Difference: 22.12431440107968 %

In [18]:
 # Inference
df_cnn['inference_time_ms'].describe()

count    26111.000000
mean         1.882758
std          1.341724
min          0.345520
25%          0.881797
50%          1.373282
75%          2.818932
max         49.664948
Name: inference_time_ms, dtype: float64