In [1]:
import pandas as pd

## Load Data

In [2]:
df_normal = pd.read_csv('Normal.csv')
df_classification = pd.read_csv('Classification.csv')
df_time_series = pd.read_csv('TimeSeries.csv')

df_normal.head()

,timestamp,cpu_usage,memory_usage,temperature,battery_level,battery_drain,battery_charging,upload_speed_kbps,download_speed_kbps,screen_on,brightness
0,2026-06-05 04:52:23,55,65,32.3,54,-103.0,0,0.000000,0.000000,1,23
1,2026-06-05 04:52:27,45,65,32.3,54,-156.0,0,0.029151,0.000000,1,23
2,2026-06-05 04:52:31,24,65,32.3,54,-94.0,0,0.027174,0.012616,1,23
3,2026-06-05 04:52:35,92,67,32.3,54,-1064.0,0,1.326250,2.359120,1,23
4,2026-06-05 04:52:39,49,66,32.3,54,-313.0,0,18.281378,16.778412,1,23

In [3]:
df_classification.head()

,timestamp,cpu_usage,memory_usage,temperature,battery_level,battery_current_mA,battery_charging,upload_speed_kbps,download_speed_kbps,screen_on,brightness,class,confidence,inference_time_ms
0,2026-06-05 07:46:45,76,69,34.7,78,-161.0,0,0.000000,0.000000,1,23,Interpreter not initialized,-1.000000,0.000000
1,2026-06-05 07:46:49,71,70,34.7,77,-306.0,0,0.475307,0.213888,1,23,Compute-Heavy Activity,0.966797,3.519323
2,2026-06-05 07:46:53,26,70,34.7,77,-287.0,0,0.702969,0.144099,1,23,Low Activity,0.835449,14.961458
3,2026-06-05 07:46:57,69,70,34.7,77,-259.0,0,0.412605,0.174007,1,23,Compute-Heavy Activity,0.901855,2.510156
4,2026-06-05 07:47:01,41,69,34.7,77,-216.0,0,0.713679,0.075944,1,23,Low Activity,0.808105,2.807240

In [4]:
df_time_series.head()

,timestamp,cpu_usage,memory_usage,temperature,battery_level,battery_charging,upload_speed_kbps,download_speed_kbps,screen_on,brightness,battery_drain,predicted_drain_average,inference_time_ms
0,2026-06-05 09:43:27,43,63,34.6,55,0,0.043597,0.000000,1,23,-117.0,-166.97115,10.906511
1,2026-06-05 09:43:31,31,63,34.6,55,0,0.353441,0.000000,1,23,-163.0,-174.10092,2.401771
2,2026-06-05 09:43:35,47,64,34.6,55,0,0.793245,0.036276,1,23,-268.0,-162.10022,1.573907
3,2026-06-05 09:43:39,32,64,34.6,55,0,0.442786,0.000000,1,23,-165.0,-165.95706,1.562136
4,2026-06-05 09:43:43,32,64,34.6,55,0,0.398597,0.000000,1,23,-263.0,-156.03537,1.478386

## Analysis

In [8]:
summary = pd.DataFrame({
    'Scenario': ['Normal', 'Classification', 'Time Series'],

    'CPU Mean (%)': [
        df_normal['cpu_usage'].mean(),
        df_classification['cpu_usage'].mean(),
        df_time_series['cpu_usage'].mean()
    ],

    'Memory Mean (%)': [
        df_normal['memory_usage'].mean(),
        df_classification['memory_usage'].mean(),
        df_time_series['memory_usage'].mean()
    ],

    'Temperature Mean (°C)': [
        df_normal['temperature'].mean(),
        df_classification['temperature'].mean(),
        df_time_series['temperature'].mean()
    ]
})

print(summary.round(2))

         Scenario  CPU Mean (%)  Memory Mean (%)  Temperature Mean (°C)
0          Normal         40.16            67.84                  32.80
1  Classification         40.78            63.31                  35.08
2     Time Series         43.12            66.24                  37.26