# Cluster Interpretation

## Import Library

In [1]:
import pandas as pd

## Load Dataset

In [2]:
df = pd.read_csv('../data/result/Original.csv')
df.head()

,timestamp,cpu_usage,memory_usage,temperature,battery_drain,upload_speed_kbps,download_speed_kbps,Target
0,2026-03-09 00:18:05,60.0,63.0,36.8,-223.0,0.000000,0.000000,0
1,2026-03-09 00:18:13,60.0,67.0,36.8,-417.0,0.000000,0.000000,1
2,2026-03-09 00:18:17,65.0,67.0,36.4,-436.0,0.394765,0.768830,1
3,2026-03-09 00:18:21,52.0,67.0,36.4,-320.0,0.401153,0.540071,0
4,2026-03-09 00:18:25,56.0,65.0,36.4,-324.0,0.000000,0.000000,0

## Cluster Summary

In [3]:
cluster_analysis = df.drop(columns=['timestamp']).groupby('Target').agg(['mean'])
df_analysis = cluster_analysis.reset_index()
df_analysis.head()

,Target,cpu_usage,memory_usage,temperature,battery_drain,upload_speed_kbps,download_speed_kbps
,,mean,mean,mean,mean,mean,mean
0,0,38.254239,72.698765,33.330679,-192.421673,1.065322,3.283031
1,1,56.184288,77.563908,35.020656,-356.063329,1.397557,7.127073
2,2,49.544304,74.873589,33.906740,-301.599213,7.079933,60.533346

## Interpretation
### Introduction
Based on the result of the K-Means clustering process with PCA transformation, the model produce three clusters (K = 3) representing different device workload conditions. The number of cluster is based on the Elbow Method analysis, which indicated the optimal number of cluster is 3 clusters, this the number of cluster pocked is 3 Clusters.
- CPU Usage (%)
- Memory Usage (%)
- Temperature (°C)
- Battery Current (mA)
- Upload Speed (kbps)
- Download Speed (kbps)

### Cluster Characteristic
#### Label 0 (Low Activity State)
Cluster 0 represents periods of minimal device activity characterized by:

- Lowest CPU and temperature → minimal processing
- Very low network throughput → little to no user interaction
- Lowest battery drain → energy-efficient state

This condition typically occurs when the device is idle or running only background services.

#### Label 1 (High Computational Workload)
Cluster 1 represents CPU/memory-heavy workloads, not network-heavy ones.

- Highest CPU + memory → active processing
- Highest temperature → sustained compute load
- Low–moderate network → not bandwidth-driven
- Highest battery drain overall

This condition typically corresponds to heavy workload such as gaming or heavy app usage.

#### Label 2 (Network-Intensive Condition)
Cluster 2 represents periods where network traffic dominates system behavior, characterized by:

- Extremely high download throughput → dominant feature
- Moderate CPU usage → processing + network handling
- Battery drain high, but less than Cluster 1

This condition commonly occurs during activities such as video streaming, large file downloads, cloud synchronization, or continuous online media consumption (e.g., YouTube or TikTok).

### Clustering Validation
To evaluate the clustering quality, the following validation metrics were used:

- Silhouette Score: 0.453
- Davies Bouldin Index: 0.784
- Calinski Harabasz Score: 32023.033