# Cluster Interpretation

## Import Library

In [1]:
import pandas as pd

## Load Dataset

In [2]:
df = pd.read_csv('../data/result/Original.csv')
df.head()

,timestamp,cpu_usage,memory_usage,temperature,battery_drain,upload_speed_kbps,download_speed_kbps,Target
0,2026-02-22 17:29:51,77.0,75.0,33.2,-308.0,0.000000,0.000000,0
1,2026-02-22 17:30:03,93.0,75.0,33.2,-441.0,7.612117,111.012924,0
2,2026-02-22 17:30:15,50.0,75.0,33.2,-296.0,0.842276,0.141110,1
3,2026-02-22 17:30:19,41.0,75.0,33.2,-229.0,1.752412,0.295840,1
4,2026-02-22 17:30:23,41.0,77.0,33.2,-224.0,1.551054,0.921999,1

## Cluster Summary

In [3]:
cluster_analysis = df.drop(columns=['timestamp']).groupby('Target').agg(['mean', 'min', 'max'])
df_analysis = cluster_analysis.reset_index()
df_analysis.head()

  Target  cpu_usage              memory_usage             temperature        \
               mean   min    max         mean   min   max        mean   min
0      0  71.078029  32.0  100.0    78.915811  69.0  82.0   35.364066  32.0
1      1  40.378378  24.0  100.0    71.744144  61.0  79.0   33.519640  32.0

        battery_drain              upload_speed_kbps                 \
    max          mean    min   max              mean  min       max
0  38.4   -525.414784 -987.0 -82.0          1.393204  0.0  8.844257
1  38.4   -229.884685 -814.0 -10.0          1.730571  0.0  8.990784

  download_speed_kbps
                 mean  min        max
0           19.191334  0.0  133.72989
1           24.206781  0.0  129.80138

## Interpretation
### Introduction
Based on the result of the K-Means clustering process, the model produce two cluster (K = 2) representing different device workload conditions. The number of cluster is based on the Elbow Method analysis, which indicated the optimal number of cluster is 3 clusters, but after verifying the number of cluster, it was concluded that the number of clusters chosen is 2 because of its high metrics evaluation. The clustering process utilized the following features:
- CPU Usage (%)
- Memory Usage (%)
- Temperature (°C)
- Battery Current (mA)
- Upload Speed (kbps)
- Download Speed (kbps)

### Cluster Characteristic
#### Label 0 (High Load Condition)
Cluster 0 represent period of high device workload characterized by:

- Higher average CPU and Memory usage compare to other clusters
- Higher battery drain due to its need to power more the CPU
- Average Network Consumption

This condition typically occurs during resource-intensive activities such as gaming or multitasking applications that require significant processing power
#### Label 1 (Low Load Condition)
Cluster 1 represent periods of low device workload characterized by:

- Lower CPU and Memory usage compare to other clusters
- Lower battery drain due to its lack of hardware usage
- Higher network usage in terms of upload and download

This condition commonly occurs during activities such as social media browsing or video streaming (e.g., YouTube or TikTok), where network usage is dominant but processing demand remains low.

### Clustering Validation
To evaluate the clustering quality, the following validation metrics were used:

- Silhouette Score: 0.46
- Davies Bouldin Index: 0.91
- Calinski Harabasz Score: 998.31