# Cluster Interpretation

## Import Library

In [1]:
import pandas as pd

## Load Dataset

In [2]:
df = pd.read_csv('../data/result/Original.csv')
df.head()

,timestamp,cpu_usage,memory_usage,temperature,battery_drain,upload_speed_kbps,download_speed_kbps,Target
0,2026-02-28 12:50:59,62.0,67.0,34.6,-111.0,0.000000,0.000000,1
1,2026-02-28 12:51:19,48.0,69.0,34.5,-445.0,0.747468,0.096831,1
2,2026-02-28 12:51:27,54.0,69.0,34.5,-194.0,0.306420,0.280683,1
3,2026-02-28 12:51:39,36.0,69.0,34.5,-196.0,1.805330,0.618360,1
4,2026-02-28 12:51:43,39.0,69.0,34.5,-198.0,2.244640,1.684146,1

## Cluster Summary

In [4]:
cluster_analysis = df.drop(columns=['timestamp']).groupby('Target').agg(['mean'])
df_analysis = cluster_analysis.reset_index()
df_analysis.head()

,Target,cpu_usage,memory_usage,temperature,battery_drain,upload_speed_kbps,download_speed_kbps
,,mean,mean,mean,mean,mean,mean
0,0,57.469477,78.383721,35.896221,-381.318314,0.937538,5.526199
1,1,40.068352,74.044007,34.396629,-236.674157,1.187713,6.857981
2,2,52.452690,72.810761,34.781633,-348.035250,5.108231,75.687426

## Interpretation
### Introduction
Based on the result of the K-Means clustering process with PCA transformation, the model produce three clusters (K = 3) representing different device workload conditions. The number of cluster is based on the Elbow Method analysis, which indicated the optimal number of cluster is 3 clusters, this the number of cluster pocked is 3 Clusters.
- CPU Usage (%)
- Memory Usage (%)
- Temperature (°C)
- Battery Current (mA)
- Upload Speed (kbps)
- Download Speed (kbps)

### Cluster Characteristic
#### Label 0 (High Load Condition)
Cluster 0 represent period of high device workload characterized by:

- Higher average CPU and Memory usage compare to other clusters
- Higher battery drain due to its need to power more the CPU
- Average Network Consumption

This condition typically occurs during resource-intensive activities such as gaming or multitasking applications that require significant processing power

#### Label 1 (Normal Usage Condition)
Cluster 1 represents periods of regular device operation characterized by:

- Moderate to lower CPU and memory usage
- Lower battery drain relative to other clusters
- Balanced or moderate network activity

This condition commonly occurs during everyday usage such as messaging, web browsing, or light application interaction. The device remains in a stable baseline operating state without any dominant resource demand.

#### Label 2 (Network-Intensive Condition)
Cluster 2 represents periods where network activity dominates device behavior, characterized by:

- Moderate CPU and memory usage
- High download and upload network traffic
- Increased battery drain primarily driven by network communication rather than computation

This condition typically occurs during activities such as video streaming, large downloads, cloud synchronization, or continuous online media consumption (e.g., YouTube or TikTok), where network interfaces contribute significantly to energy usage.

### Clustering Validation
To evaluate the clustering quality, the following validation metrics were used:

- Silhouette Score: 0.437
- Davies Bouldin Index: 0.777
- Calinski Harabasz Score: 2095.709